### ISSUE TITLE
Nested anchoring

### ISSUE THREAD

**Issue by Jerrik** [BeSite/jQuery.dotdotdot#50]
If using after: 'a.readmore' and there happens to be a < a href >Example text< / a > at the cutoff of text to be cropped the a.readmore gets placed inside of < a href >Example text< / a >

Result: < a href >Example text < a class="readmore" >Read More< / a >< / a >
Should be: < a href >Example text < / a >< a class="readmore">Read More< / a >

**Comment by ImBobby** [comment]
Tried to reproduce @Jerrik's issue. adding `a` to line 344 doesn't solve the issue. 

Here's the screenshot.
![screen shot 2015-01-05 at 8 02 57 am](https://cloud.githubusercontent.com/assets/2084193/5608282/4f6bb72a-94b1-11e4-8d01-1bbe347355aa.png)

**Comment by Jerrik** [comment]
Sorry for the delay. Your fix did solve the issue. I added anchor tag var notx.
Tested on the demo file.

@ImBobby The above screenshot shows text hyper-linked but when you mouse over do u get the same url for all of it? It could seem to be one link but really isn't. This was at least my case, I almost fell for it.

**Comment by FrDH** [comment]
Ok, should be fixed in version 1.7.2
