### ISSUE TITLE
Problem in Chrome browser

### ISSUE THREAD

**Issue by JuanDaniel** [BeSite/jQuery.dotdotdot#56]
Hello, i am using the plugin and i think it is amazing. Every worked fine until i tested over the Chrome browser version 39.0.2171.71.
The problem is that when the page load the plugin not work, but when i change the  browser's window, the plugin work fine.
Anybody can help me?

**Comment by FrDH** [comment]
Chrome fires the onDocumentReady event before having retrieved the width and height of images from the server. So if your content has images in it, make sure to give it a width and height.

If that doesn't solve your problem, you could trigger the plugin to update its appearance onWindowLoad, which is fired after every element on the page has been loaded:
````javascript
$(document).ready(function() {
   $(".text").dotdotdot();
});

$(window).load(function() {
   $(".text").trigger( "update.dot" );
});
````

**Comment by JuanDaniel** [comment]
Tanks you, with your tip i solved the problem.
Regards!!
