### ISSUE TITLE
Doesnt work properly with multiple columns

### ISSUE THREAD

**Issue by Vontera** [BeSite/jQuery.dotdotdot#57]
In my webpage, I have lot of paragraphs of text, split into columns. When I apply your dotdotdot plugin to it, it doesnt work as expected. The overflowing text is not really hiding.

This is happening on Firefox v35  on Windows 8.1.

Snapshot: http://i.imgur.com/Yf5HzrF.png

**Comment by FrDH** [comment]
I'd say the script should work when using css columns. Does it only not work on FireFox? Or haven't you checked other browsers?
Is there an online demo I could have a look at?
