### ISSUE TITLE
Doesn't work with "br"

### ISSUE THREAD

**Issue by cameronprattedwards** [BeSite/jQuery.dotdotdot#58]
If I have content that looks like this:

```html
	<div class="content">
		<p>Drop a verse.</p>
		<p><br/></p>
		<p>Line 2</p>
		<p><br/></p>
		<p>Line 3</p>
	</div>
```

with styling like this:

```css
	.content {
		max-height: 50px;
		overflow: hidden;
	}
```

No ellipsis is added after the first line. Like this (in Chrome):

![screen shot 2015-01-22 at 3 35 08 pm](https://cloud.githubusercontent.com/assets/5456216/5864022/4f135640-a24c-11e4-8c00-1ab307f6c1c4.png)

If I replace the `<br/>`s with `<span></span>`s, the ellipsis works fine. I unfortunately don't have control over the content that gets truncated.

I tried fixing the bug myself, but I'm in over my head. It seems the problem is that the `ellipsisElement` function is never getting called, meaning [this line](https://github.com/BeSite/jQuery.dotdotdot/blob/master/src/js/jquery.dotdotdot.js#L380) never evaluates to `true`.

**Comment by FrDH** [comment]
Hmm, I see the issue but can't really think of a way to fix it.
Maybe you can replace the `<br />` with a `<span></span>` using jQuery before firing the plugin?
````javascript
$(".content").find( "br" ).replaceWith( "<span />" );
$(".content").dotdotdot();
````

**Comment by bolshchikov** [comment]
@cameronprattedwards, you can set a css property `word-break` on your `p` tag, and no need in `br` tags, or just remove them before applying plugin.
