### ISSUE TITLE
Issues when using max-height

### ISSUE THREAD

**Issue by velocirabbit** [BeSite/jQuery.dotdotdot#59]
When using watch to update the truncation when the div size is changed, it doesn't seem like it plays well with max-height. For example, let's say there's a <div> that's originally truncated to 4 lines max, but drops down to, say, 1 line max (or even no lines if you want to hide the <div> and remove its space from the DOM while keeping it animated) when the <div> is hovered over, and returns back to 4 lines max when you unhover. The expected result is that the <div> so expand up to 4 lines again and redo the truncation, but since max-height doesn't actually change the height of the <div> if it's less than the value of max-height, the <div> is stuck being truncated to 1 line.

Is there any way to get around this without having a fixed value for the height?

**Comment by FrDH** [comment]
No, max-height probably won't work, the wrapper needs a fixed height while the plugin calculates where to cut off the text.
I guess you could set a fixed height to the wrapper before firing the plugin and remove it afterwards:
````javascript
$(".wrapper")
    .height( 150 )
    .dotdotdot()
    .height( "auto" );
````
