### ISSUE TITLE
License ambiguity

### ISSUE THREAD

**Issue by rogerbinns** [BeSite/jQuery.dotdotdot#61]
http://dotdotdot.frebsite.nl/

The bottom of the page says the plugin is dual MIT/GPL licensed.  But above that it says:

    The jQuery.dotdotdot plugin is created as donationware
    and is free to use in personal or non-profit projects

However the MIT/GPL license means it is free to use in virtually all projects including for profit ones.  If you consider the text above as part of the license then you need to remove at least the GPL since they are contradictory.

I suggest you alter to whole donationware paragraph to something like this:

    Donations towards this project are greatly appreciated, but not required.

**Comment by FrDH** [comment]
I agree it's a bit vague and contradictory, I'll update and the license the website late on.
