### ISSUE TITLE
'HTMLElement' is undefined.

### ISSUE THREAD

**Issue by newpen** [BeSite/jQuery.dotdotdot#63]
When using it on IE 8, it shows an error message of 'HTMLElement' is undefined.

Looking at the details of the error, it should be line 70
if ( typeof c == 'string' || c instanceof HTMLElement )
causing the problem,

**Comment by gpetrioli** [comment]
+1, I am having the same problem. 
An alternative (*for the plugin*) can be found at http://stackoverflow.com/questions/5747523/cross-browser-solution-for-checking-if-a-javascript-object-is-an-html-element

(*or state that it does not support IE8*)

**Comment by gpetrioli** [comment]
I have create a pull request that fixes the issue. 

Checking for existence of `nodeType` and that its value is `1` is a crossbrowser way to detect it.
