### ISSUE TITLE
Read More Gets Hidden When Last Row of Text is Short

### ISSUE THREAD

**Issue by bryannovoed** [BeSite/jQuery.dotdotdot#66]
The plugin seems to remove what was was specified to be kept in after. When the text is a long paragraph, there doesn't seem to be an issue. When the paragraph that gets split is short, the following happens: http://jsfiddle.net/64qq5xvy/2/ and the "Read More" anchor tag is removed.

**Comment by FrDH** [comment]
The jsfiddle isn't doing anything at all, there's an error: "TypeError: url.indexOf is not a function".
