### ISSUE TITLE
Read More Link inside of content link.

### ISSUE THREAD

**Issue by saiichihashimoto** [BeSite/jQuery.dotdotdot#67]
I use dotdotdot on an element.
That element contains a link (let's call that link JIMMY) and a readmore link (let's call that link BOB).
I make sure to use the "after" parameter when calling dotdotdot to specify BOB.
dotdotdot happens to truncate in the middle of JIMMY.
I'd expect BOB to be after JIMMY.
BOB ends up inside of JIMMY.
JIMMY isn't happy.

**Comment by FrDH** [comment]
That's odd, on line 343 a link ("a") is specified. So BOB should have been added after JIMMY.

**Comment by FrDH** [comment]
Ok, found the issue.
`a table, etc` should have been `a, table, etc`.
Will release a new version soon.

**Comment by saiichihashimoto** [comment]
Cool! I'm looking forward to this issue getting closed.

**Comment by FrDH** [comment]
The bug has been fixed in the latest version. Closing this issue now.

**Comment by howlingmad** [comment]
this isn't fixed

**Comment by howlingmad** [comment]
demo: http://codepen.io/howlingmad/pen/vOeoGd
