### ISSUE TITLE
Read more link disappear after window size change

### ISSUE THREAD

**Issue by rob006** [BeSite/jQuery.dotdotdot#68]
I use plugin to truncate too long leads from news. After every lead I have "read more" link. Also I use `watch: "window"`. 
After refreshing page everything is OK: long leads has been truncated with "read more" link at the end, short leads are untouched with "read more" link at the end. But when size of window has been changed, "read more" links from leads that doesn't need to be truncated are disappear. Truncated leads works OK, short leads has only lead content without "read more" link. 
How to always keep "read more" link at the end of lead?

**Comment by FrDH** [comment]
Is there an online example? I tried but could not reproduce the issue with the demo files.

**Comment by rob006** [comment]
http://salenauts.com/

**Comment by FrDH** [comment]
Can you post the script you're using? I can't figure out why it's working OK in the demo files but not on your website.

**Comment by rob006** [comment]
Here you can find demo with this bug (dot3): https://github.com/rob006/jQuery.dotdotdot/blob/master/index.html
It looks like problem is putting more link inside `<p>` tag.

**Comment by FrDH** [comment]
Sounds like an odd bug. I can't think of any reason for it to happen.
I guess you could try to remove the `<p>` or to fire the plugin on the `<p>` instead of the `<div>`. Maybe that'll improve the behavior.

**Comment by rob006** [comment]
I need to handle multiple `<p>` tags in lead, so I can't use any of those solutions. 
Anyway, when I put more-link outside `<p>` tag, after initialisation it is moved inside `<p>` tag, so the DOM HTML looks exactly the same as in bugged demo file, but after window resize everything works fine. 
Also this line looks suspicious: https://github.com/BeSite/jQuery.dotdotdot/blob/master/src/js/jquery.dotdotdot.js#L396 - why `after` is detached if element is not truncated?
