### ISSUE TITLE
trigger('update.dot') seems does not work

### ISSUE THREAD

**Issue by hellsingblack** [BeSite/jQuery.dotdotdot#69]
I initialise my dotdotdot like that 

$(sectionSelector).dotdotdot({
                    after: seemoreUi,
                    height: 170,
                    callback: function (isTruncated, orgContent) {
                        if (isTruncated) {
                            seemoreUi.show();
                        }
                        else {
                            seemoreUi.hide();
                        }
                    },
                    watch: "window"
                });

when I tried to $(sectionSelector).trigger('update.dot'); the callback never call.

**Comment by FrDH** [comment]
That's odd, I think it should.
Are you getting any errors?

**Comment by hellsingblack** [comment]
no errors appear...

**Comment by FrDH** [comment]
Is there an online example?
I tried, but could not reproduce the issue with the demo files.
````javascript
alert( $('#dot4').triggerHandler('isTruncated') );
````
alerted `true`.
