### ISSUE TITLE
Whitespace between two html tags are deleted during dotdotdotification

### ISSUE THREAD

**Issue by MathieuLescure** [BeSite/jQuery.dotdotdot#70]
```
<html>
	<head>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.js"></script>
		<script src="jquery.dotdotdot.js"></script>
		<style>
			.test {
				width: 300px;
				height: 1.2em;
			}
		</style>
	</head>
	<body>
		<div class="test">Issue with the <i>Library</i> <b>Dotdotdot</b> and withespaces between tags</div>
		<script>
			$(document).ready(function() {
				$(".test").dotdotdot({});
			});
		</script>
	</body>
</html>
```
![screen shot](https://cloud.githubusercontent.com/assets/5396415/7479560/86275ff2-f330-11e4-9c09-488ceeb063f6.png)

**Comment by FrDH** [comment]
I think I found the reason and'll see if I can fix it without introducing new issues.

**Comment by matthewferry** [comment]
+1

**Comment by radicalsauce** [comment]
+1 - we're having the exact same issue. @FrDH - any insight?

**Comment by FrDH** [comment]
The latest version should have fixed this issue I think.
If it didn't, try removing the `$.trim` from line 585 and see if that makes any difference.

**Comment by matthewferry** [comment]
Yep that seemed to fixed it, thanks! Might want to close this issue?

**Comment by MathieuLescure** [comment]
The version 1.7.3 fixed the issue for me. Thank you for the library and the bug fix.
