### ISSUE TITLE
Loading extra content with AJAX, can't get update to work

### ISSUE THREAD

**Issue by tadywankenobi** [BeSite/jQuery.dotdotdot#71]
I'm using DDD to truncate content in table cells. The bottom of the table is populated with lazy loading. I'm also using the Bootstrap popout functionality to show the extra original content. It's all working fine but I can't get DDD to update when the lazy loaded content comes in.

I have to say, I find the documentation around the trigger events very light. It's not clear how exactly they work or run, so if you could provide better examples, especially around callbacks, it would be a really great help.

My code is as follows:

```javascript
$("td").dotdotdot({
                watch       : "window",
                height      : 40,
                wrap        : "word",
                callback: function (isTruncated, orgContent) {
                    if (isTruncated) {
                        $(this).mouseenter(function () {
                            $(this).attr({
                                "data-container": "body",
                                "data-toggle": "popover",
                                "data-trigger": "hover",
                                "data-content": orgContent[0].data,
                                "data-placement": "bottom"
                            });
                            $(this).popover('show');
                        }).mouseleave(function () {
                            $(this).popover('destroy');
                        });
                    }
                }
            });
```

This all works fine (although notice the orgContent[0].data... Using orgContent on it's own does NOT return a string as indictated in the documentation. This took me some time to work out).

In my later "lazy loading" function, I'm doing:

```javascript
LoadMoreRows();
$("td").trigger("update.dot");
```

Nothing happens here. The new content is loaded in the table, but the DDD function does not update.

Any suggestions as to a. what I'm doing wrong or b. what the issue might be?

Thanks a million for the support.

P.S. Sorry if it sounds like I'm having a go over the documentation, I'm not, I've just been at this all day...

**Comment by FrDH** [comment]
How are the rows loaded? If asynchronously (with an AJAX call) you'll need to wait till the HTML is actually added to the DOM. If synchronously, I can't think of a reason why triggering the `update.dot` event wouldn't work.

**Comment by tadywankenobi** [comment]
Sweet man, thanks. That whole JS blocking functions thing catches me out time and time again. You'd think I'd have learned. Added it to the $.ajax success method and it's working now.

Thanks again!
