### ISSUE TITLE
Don't replace $.fn.text and $.fn.html

### ISSUE THREAD

**Issue by cmlenz** [BeSite/jQuery.dotdotdot#73]
I was surprised to see in the source code that jQuery.dotdotdot unconditionally "swizzles" the jQuery methods `text()` and `html()`, i.e. replaces them with its own version that triggers the update event. I understand the intention and I know that these functions call through to the original, but I still think this should not be the default behavior, or they should at least be a documented way to revert these changes.

`html()` and `text()` may be called *very often* on JS heavy sites, and each of these calls incurs the cost of going through the override, even though few (or even none) of the elements actually have the dotdotdot functionality enabled.

**Comment by FrDH** [comment]
The thing is, if I remove it and some other script calls `html()` or `text()`, the ellipsis isn't updated.
But if you want, feel free to remove the lines that override the methods in your copy of dotdotdot.
