### ISSUE TITLE
"Don't put the ellipsis directly inside these elements" does not seem to work

### ISSUE THREAD

**Issue by howlingmad** [BeSite/jQuery.dotdotdot#76]
Seems to still put the ellipsis inside any of these elements. Example:
http://codepen.io/howlingmad/pen/vOeoGd

**Comment by howlingmad** [comment]
There seems to be a "sweet spot" where this fails to work properly. In this example, with a read more link. the ellipsis and the link are inserted inside another link

http://codepen.io/howlingmad/pen/vOeoWa

**Comment by FrDH** [comment]
That's pretty odd, it seems to me the "after" element is what is causing the issue.
I have no idea why though...

**Comment by howlingmad** [comment]
There is no after element in the first example, and the ellipsis still appears inside the link. I will try and dig into it a bit and see if I can work out the issue.
