### ISSUE TITLE
Element not rerendering, innerHeight not increasing -> text is out of element

### ISSUE THREAD

**Issue by pavgra** [BeSite/jQuery.dotdotdot#78]
I'm using dotdotdot with following options: {ellipsis: ' ', after: $someEl, height: someHeight, watch: true}. Sometimes it leaves more text inside element than the element can show. As i see it starts happening inside function "ellipsisElement" in while cycle when condition "!test( $i, o )" becomes positive (true) and text starts increasing. After text size increased and new text is pushed inside the element (function "setTextContent" completed) the target element is not rerendered and it's innerHeight remains as it was before. It causes the cycle to continue execution even after text is out of element. To force element rerender and innerHeight update, I added a line "$i.children().each(function() { $i.toggle().toggle() })" after the line "setTextContent( e, textArr.slice( 0, midPos + 1 ).join( separator ) + o.ellipsis );". This solves the problem.

**Comment by FrDH** [comment]
Why do you toggle `$i` while looping over all children of `$i`? Shouldn't you toggle `$(this)`?
Or, if toggling `$i` is enough to solve the issue, toggle it only once?
