### ISSUE TITLE
Pass "height" option as function

### ISSUE THREAD

**Issue by pavgra** [BeSite/jQuery.dotdotdot#79]
It would be cool to be able to pass not number but function as "height" parameter.

To add such feature the following code:

"opts.maxHeight = ( typeof opts.height == 'number' )
	? opts.height
	: getTrueInnerHeight( $dot );"

needs to be relpaced with

"if (typeof opts.height == 'number')
	opts.maxHeight = opts.height;
else if (typeof opts.height == 'function')
	opts.maxHeight = opts.height();
else
	opts.maxHeight = getTrueInnerHeight( $dot );"

**Comment by FrDH** [comment]
Thank you for the suggestion.
I'll see if I can implement this is the next version.

**Comment by rvalitov** [comment]
Seems that it was fixed. The issue can be closed, I guess. The documentation seems outdated, some update required.
