### ISSUE TITLE
Not truncating the content when the first word is lengthier than the container

### ISSUE THREAD

**Issue by h-hub** [BeSite/jQuery.dotdotdot#80]
When we use  'word' as the wrap-option and the first word of the paragraph is lengthier than than container, the word breaks from the middle. My requirement is to never break a word from the middle.

**Comment by FrDH** [comment]
Try setting the `fallbackToLetter` option to `false`.

**Comment by h-hub** [comment]
I did. But it is not working.

**Comment by FrDH** [comment]
Then I don't think there's a solution for your issue (or at least not using this plugin).
